"""
Infographic Generator
Produces a one-page SVG company-fit summary from the LLM's JSON output.
"""


def generate_infographic_svg(data: dict) -> str:
    """
    data keys: company_name, role_title, pros (list), cons (list), fit_score (1-10)
    Returns an SVG string.
    """
    company = data.get("company_name", "Company")
    role = data.get("role_title", "Role")
    pros = data.get("pros", [])[:4]
    cons = data.get("cons", [])[:4]
    score = min(max(int(data.get("fit_score", 5)), 1), 10)

    # Score color: green if >=7, yellow if >=5, red otherwise
    score_color = "#22c55e" if score >= 7 else ("#f59e0b" if score >= 5 else "#ef4444")
    score_pct = score * 10  # for the arc

    def wrap(text: str, max_len: int = 38) -> list[str]:
        """Simple word-wrap."""
        words = text.split()
        lines, current = [], ""
        for w in words:
            if len(current) + len(w) + 1 <= max_len:
                current = (current + " " + w).strip()
            else:
                if current:
                    lines.append(current)
                current = w
        if current:
            lines.append(current)
        return lines or [""]

    def pro_rows(items):
        rows = ""
        for i, item in enumerate(items):
            y = 370 + i * 52
            lines = wrap(item)
            rows += f'<rect x="40" y="{y}" width="320" height="44" rx="8" fill="#dcfce7"/>'
            rows += f'<text x="70" y="{y + 16}" font-size="11" fill="#166534">✔</text>'
            for j, line in enumerate(lines[:2]):
                rows += f'<text x="90" y="{y + 16 + j * 14}" font-size="11" fill="#166534">{line}</text>'
        return rows

    def con_rows(items):
        rows = ""
        for i, item in enumerate(items):
            y = 370 + i * 52
            lines = wrap(item)
            rows += f'<rect x="400" y="{y}" width="320" height="44" rx="8" fill="#fee2e2"/>'
            rows += f'<text x="430" y="{y + 16}" font-size="11" fill="#991b1b">✘</text>'
            for j, line in enumerate(lines[:2]):
                rows += f'<text x="450" y="{y + 16 + j * 14}" font-size="11" fill="#991b1b">{line}</text>'
        return rows

    # Gauge arc — simple approximation using a circle stroke-dasharray
    circumference = 314  # pi * 2 * 50
    dash = int((score_pct / 100) * circumference)

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="760" height="620" viewBox="0 0 760 620" font-family="Arial, sans-serif">
  <!-- Background -->
  <rect width="760" height="620" rx="16" fill="#f8fafc"/>

  <!-- Header band -->
  <rect width="760" height="110" rx="16" fill="#1a1a2e"/>
  <rect y="94" width="760" height="16" fill="#1a1a2e"/>

  <!-- Title -->
  <text x="380" y="48" text-anchor="middle" font-size="22" font-weight="bold" fill="white">{company}</text>
  <text x="380" y="76" text-anchor="middle" font-size="14" fill="#94a3b8">{role}</text>

  <!-- Fit Score gauge -->
  <circle cx="380" cy="220" r="70" fill="none" stroke="#e2e8f0" stroke-width="14"/>
  <circle cx="380" cy="220" r="70" fill="none" stroke="{score_color}" stroke-width="14"
          stroke-dasharray="{dash} {circumference}" stroke-dashoffset="78"
          transform="rotate(-90 380 220)"/>
  <text x="380" y="212" text-anchor="middle" font-size="36" font-weight="bold" fill="{score_color}">{score}</text>
  <text x="380" y="234" text-anchor="middle" font-size="13" fill="#64748b">/ 10 Fit Score</text>

  <!-- Column headers -->
  <text x="200" y="348" text-anchor="middle" font-size="14" font-weight="bold" fill="#166534">PROS</text>
  <text x="560" y="348" text-anchor="middle" font-size="14" font-weight="bold" fill="#991b1b">CONS</text>
  <line x1="380" y1="330" x2="380" y2="610" stroke="#e2e8f0" stroke-width="1"/>

  <!-- Pros -->
  {pro_rows(pros)}

  <!-- Cons -->
  {con_rows(cons)}

  <!-- Footer -->
  <text x="380" y="608" text-anchor="middle" font-size="10" fill="#94a3b8">Generated by Job Pack</text>
</svg>"""

    return svg
